config/routes.rb
Rails.application.routes.draw do

  get 'flats/:id', to: 'flats#show', as: :flat

  root to: 'flats#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  before_action :fetch_flats

  def index
  end

  def show
    id = params[:id].to_i
    @flat = @flats.select { |f| f['id'] == id }.first
  end

  private

  def fetch_flats
    @flats = JSON.parse(open(URL).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <h1>Flats</h1>
  <ul class="list-group">


    <% @flats.each do |flat| %>
    <li class="list-group-item">
      <%= link_to flat_path(flat['id']) do %>
      <div class="card-trip">
        <img src="<%= flat['imageUrl'] %>" />
        <div class="card-trip-infos">
          <div>
            <h2><%= flat['name'] %></h2>
          </div>
          <h2 class="card-trip-pricing">$<%= flat['price'] %></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
      </div>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

app/views/flats/show.html.erb
<h1><%= @flat['name'] %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>